-- Organización, establecimientos, almacenes, POS y profesionales.
-- Se enriquecen datos fiscales, operativos y sanitarios sin mezclar autorización con el establecimiento.

CREATE TABLE sch_farmacia.empresa_operadora (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    ruc                 VARCHAR(11) NOT NULL,
    razon_social        VARCHAR(300) NOT NULL,
    nombre_comercial    VARCHAR(300),
    direccion_fiscal    VARCHAR(500),
    ubigeo_fiscal       VARCHAR(10),
    telefono            VARCHAR(40),
    email               CITEXT,
    sitio_web           VARCHAR(300),
    logo_uri            TEXT,
    moneda_funcional    CHAR(3) NOT NULL DEFAULT 'PEN',
    zona_horaria        VARCHAR(80) NOT NULL DEFAULT 'America/Lima',
    permite_venta_online BOOLEAN NOT NULL DEFAULT FALSE,
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_empresa_operadora PRIMARY KEY (id),
    CONSTRAINT uk_empresa_operadora_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_empresa_operadora_tenant_ruc UNIQUE (tenant_id, ruc),
    CONSTRAINT uk_empresa_operadora_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_empresa_operadora_tenant FOREIGN KEY (tenant_id)
        REFERENCES sch_farmacia.tenant(id),
    CONSTRAINT ck_empresa_operadora_ruc CHECK (char_length(ruc) = 11),
    CONSTRAINT ck_empresa_operadora_estado CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
);

CREATE TABLE sch_farmacia.establecimiento_farmaceutico (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    codigo              VARCHAR(40) NOT NULL,
    nombre              VARCHAR(250) NOT NULL,
    tipo_establecimiento VARCHAR(40) NOT NULL,
    categoria_regulatoria_codigo VARCHAR(50),
    direccion           VARCHAR(500),
    ubigeo              VARCHAR(10),
    referencia          VARCHAR(300),
    latitud             NUMERIC(10,7),
    longitud            NUMERIC(10,7),
    telefono            VARCHAR(40),
    email               CITEXT,
    es_principal        BOOLEAN NOT NULL DEFAULT FALSE,
    permite_venta_online BOOLEAN NOT NULL DEFAULT FALSE,
    permite_delivery    BOOLEAN NOT NULL DEFAULT FALSE,
    perfil_operacion    VARCHAR(30) NOT NULL DEFAULT 'ONLINE',
    zona_horaria        VARCHAR(80) NOT NULL DEFAULT 'America/Lima',
    estado_operativo    VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_establecimiento_farmaceutico PRIMARY KEY (id),
    CONSTRAINT uk_establecimiento_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_establecimiento_tenant_codigo UNIQUE (tenant_id, codigo),
    CONSTRAINT uk_establecimiento_scope_id UNIQUE (tenant_id, empresa_id, id),
    CONSTRAINT fk_establecimiento_empresa FOREIGN KEY (tenant_id, empresa_id)
        REFERENCES sch_farmacia.empresa_operadora(tenant_id, id),
    CONSTRAINT ck_establecimiento_perfil CHECK (perfil_operacion IN ('ONLINE','STORE_EDGE')),
    CONSTRAINT ck_establecimiento_estado CHECK (estado_operativo IN ('ACTIVO','INACTIVO','SUSPENDIDO','CERRADO'))
);

CREATE TABLE sch_farmacia.establecimiento_autorizacion_sanitaria (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    tipo_autorizacion   VARCHAR(50) NOT NULL,
    numero_autorizacion VARCHAR(100) NOT NULL,
    entidad_emisora     VARCHAR(150),
    fecha_emision       DATE,
    vigente_desde       DATE,
    vigente_hasta       DATE,
    estado              VARCHAR(20) NOT NULL DEFAULT 'VIGENTE',
    observacion         VARCHAR(1000),
    evidencia_uri       TEXT,
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_establecimiento_autorizacion PRIMARY KEY (id),
    CONSTRAINT uk_establecimiento_autorizacion_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_est_autorizacion_numero UNIQUE (tenant_id, establecimiento_id, tipo_autorizacion, numero_autorizacion),
    CONSTRAINT fk_establecimiento_autorizacion_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id)
        REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT ck_establecimiento_autorizacion_fechas CHECK (vigente_hasta IS NULL OR vigente_desde IS NULL OR vigente_hasta >= vigente_desde),
    CONSTRAINT ck_establecimiento_autorizacion_estado CHECK (estado IN ('VIGENTE','VENCIDA','SUSPENDIDA','REVOCADA'))
);

CREATE TABLE sch_farmacia.almacen (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    codigo              VARCHAR(40) NOT NULL,
    nombre              VARCHAR(150) NOT NULL,
    tipo                VARCHAR(30) NOT NULL DEFAULT 'VENTA',
    permite_lotes       BOOLEAN NOT NULL DEFAULT TRUE,
    permite_vencimiento BOOLEAN NOT NULL DEFAULT TRUE,
    permite_venta       BOOLEAN NOT NULL DEFAULT FALSE,
    permite_despacho    BOOLEAN NOT NULL DEFAULT TRUE,
    control_temperatura BOOLEAN NOT NULL DEFAULT FALSE,
    temperatura_min_c   NUMERIC(6,2),
    temperatura_max_c   NUMERIC(6,2),
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_almacen PRIMARY KEY (id),
    CONSTRAINT uk_almacen_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_almacen_est_codigo UNIQUE (tenant_id, establecimiento_id, codigo),
    CONSTRAINT uk_almacen_scope_id UNIQUE (tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_almacen_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id)
        REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT ck_almacen_temperatura CHECK (temperatura_max_c IS NULL OR temperatura_min_c IS NULL OR temperatura_max_c >= temperatura_min_c),
    CONSTRAINT ck_almacen_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE sch_farmacia.ubicacion_almacen (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    almacen_id          BIGINT NOT NULL,
    codigo              VARCHAR(50) NOT NULL,
    zona                VARCHAR(80),
    pasillo             VARCHAR(40),
    rack                VARCHAR(40),
    nivel               VARCHAR(40),
    posicion            VARCHAR(40),
    descripcion         VARCHAR(200),
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ubicacion_almacen PRIMARY KEY (id),
    CONSTRAINT uk_ubicacion_almacen_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_ubicacion_almacen_codigo UNIQUE (tenant_id, almacen_id, codigo),
    CONSTRAINT uk_ubicacion_scope_id UNIQUE (tenant_id, empresa_id, establecimiento_id, almacen_id, id),
    CONSTRAINT fk_ubicacion_almacen FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, almacen_id)
        REFERENCES sch_farmacia.almacen(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT ck_ubicacion_almacen_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE sch_farmacia.terminal_pos (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    codigo              VARCHAR(40) NOT NULL,
    nombre              VARCHAR(120),
    numero_serie_equipo VARCHAR(120),
    hostname            VARCHAR(150),
    ip_equipo           INET,
    impresora_codigo    VARCHAR(100),
    store_edge_habilitado BOOLEAN NOT NULL DEFAULT FALSE,
    ultimo_heartbeat_at TIMESTAMPTZ,
    version_app         VARCHAR(80),
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_terminal_pos PRIMARY KEY (id),
    CONSTRAINT uk_terminal_pos_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_terminal_pos_codigo UNIQUE (tenant_id, establecimiento_id, codigo),
    CONSTRAINT uk_terminal_scope_id UNIQUE (tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_terminal_pos_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id)
        REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT ck_terminal_pos_estado CHECK (estado IN ('ACTIVO','INACTIVO','BLOQUEADO','MANTENIMIENTO'))
);

CREATE TABLE sch_farmacia.profesional_farmaceutico (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    tipo_documento      VARCHAR(20) NOT NULL,
    numero_documento    VARCHAR(30) NOT NULL,
    nombres             VARCHAR(150) NOT NULL,
    apellidos           VARCHAR(150) NOT NULL,
    email               CITEXT,
    telefono            VARCHAR(40),
    colegio_profesional VARCHAR(100),
    numero_colegiatura  VARCHAR(50),
    especialidad        VARCHAR(150),
    estado_colegiatura  VARCHAR(30),
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_profesional_farmaceutico PRIMARY KEY (id),
    CONSTRAINT uk_profesional_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_profesional_doc UNIQUE (tenant_id, tipo_documento, numero_documento),
    CONSTRAINT uk_profesional_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_profesional_tenant FOREIGN KEY (tenant_id)
        REFERENCES sch_farmacia.tenant(id),
    CONSTRAINT ck_profesional_estado CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
);

CREATE TABLE sch_farmacia.asignacion_profesional (
    id                  BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico        UUID NOT NULL DEFAULT uuidv7(),
    tenant_id           BIGINT NOT NULL,
    empresa_id          BIGINT NOT NULL,
    establecimiento_id  BIGINT NOT NULL,
    profesional_id      BIGINT NOT NULL,
    funcion             VARCHAR(40) NOT NULL,
    es_principal        BOOLEAN NOT NULL DEFAULT FALSE,
    vigente_desde       DATE NOT NULL,
    vigente_hasta       DATE,
    estado              VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    evidencia_uri       TEXT,
    created_by          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(100),
    updated_at          TIMESTAMPTZ,
    CONSTRAINT pk_asignacion_profesional PRIMARY KEY (id),
    CONSTRAINT uk_asignacion_profesional_uuid UNIQUE (uuid_publico),
    CONSTRAINT fk_asignacion_prof_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id)
        REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT fk_asignacion_prof_prof FOREIGN KEY (tenant_id, profesional_id)
        REFERENCES sch_farmacia.profesional_farmaceutico(tenant_id, id),
    CONSTRAINT ck_asignacion_prof_fechas CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
    CONSTRAINT ck_asignacion_prof_estado CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
);

CREATE INDEX ix_establecimiento_empresa ON sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id);
CREATE INDEX ix_asignacion_prof_est ON sch_farmacia.asignacion_profesional(tenant_id, establecimiento_id, estado);
