-- Productos controlados: receta especial, movimientos y balances.

CREATE TABLE sch_farmacia.receta_controlada (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    prescripcion_id BIGINT NOT NULL,
    clasificacion_controlada_codigo VARCHAR(40) NOT NULL,
    tipo_receta VARCHAR(50) NOT NULL,
    numero_receta VARCHAR(120),
    fecha_expedicion TIMESTAMPTZ NOT NULL,
    fecha_limite_at TIMESTAMPTZ,
    regla_vigencia_codigo VARCHAR(80),
    estado_validacion VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    motivo_invalidacion VARCHAR(1000),
    retenida BOOLEAN NOT NULL DEFAULT FALSE,
    retenida_at TIMESTAMPTZ,
    archivada_at TIMESTAMPTZ,
    conservar_hasta DATE,
    profesional_validador_id BIGINT,
    evidencia_uri TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_receta_controlada PRIMARY KEY (id),
    CONSTRAINT uk_receta_controlada_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_receta_controlada_pres UNIQUE (prescripcion_id),
    CONSTRAINT uk_receta_controlada_scope_id UNIQUE (tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_receta_controlada_pres FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, prescripcion_id) REFERENCES sch_farmacia.prescripcion(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_receta_controlada_clasif FOREIGN KEY (clasificacion_controlada_codigo) REFERENCES sch_farmacia.clasificacion_controlada(codigo),
    CONSTRAINT fk_receta_controlada_prof FOREIGN KEY (tenant_id, profesional_validador_id) REFERENCES sch_farmacia.profesional_farmaceutico(tenant_id, id),
    CONSTRAINT ck_receta_controlada_fechas CHECK (fecha_limite_at IS NULL OR fecha_limite_at >= fecha_expedicion),
    CONSTRAINT ck_receta_controlada_estado CHECK (estado_validacion IN ('PENDIENTE','VALIDA','INVALIDA','VENCIDA','ADULTERADA','ATENDIDA','ANULADA'))
);

CREATE TABLE sch_farmacia.movimiento_controlado (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    lote_id BIGINT,
    clasificacion_controlada_codigo VARCHAR(40) NOT NULL,
    tipo_movimiento VARCHAR(30) NOT NULL,
    cantidad NUMERIC(18,4) NOT NULL,
    saldo_anterior NUMERIC(18,4),
    saldo_posterior NUMERIC(18,4),
    documento_tipo VARCHAR(50) NOT NULL,
    documento_uuid UUID,
    receta_controlada_id BIGINT,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    profesional_id BIGINT,
    observacion VARCHAR(1000),
    CONSTRAINT pk_movimiento_controlado PRIMARY KEY (id),
    CONSTRAINT uk_movimiento_controlado_uuid UNIQUE (uuid_publico),
    CONSTRAINT fk_mov_controlado_sku FOREIGN KEY (tenant_id, sku_id) REFERENCES sch_farmacia.sku_comercial(tenant_id, id),
    CONSTRAINT fk_mov_controlado_lote FOREIGN KEY (tenant_id, lote_id) REFERENCES sch_farmacia.lote(tenant_id, id),
    CONSTRAINT fk_mov_controlado_clasif FOREIGN KEY (clasificacion_controlada_codigo) REFERENCES sch_farmacia.clasificacion_controlada(codigo),
    CONSTRAINT fk_mov_controlado_prof FOREIGN KEY (tenant_id, profesional_id) REFERENCES sch_farmacia.profesional_farmaceutico(tenant_id, id),
    CONSTRAINT fk_mov_controlado_receta FOREIGN KEY (receta_controlada_id) REFERENCES sch_farmacia.receta_controlada(id),
    CONSTRAINT ck_mov_controlado_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_mov_controlado_saldo CHECK (saldo_anterior IS NULL OR saldo_anterior >= 0) ,
    CONSTRAINT ck_mov_controlado_tipo CHECK (tipo_movimiento IN ('ENTRADA','SALIDA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO','DEVOLUCION','DISPOSICION'))
);

CREATE TABLE sch_farmacia.balance_controlado (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    clasificacion_controlada_codigo VARCHAR(40) NOT NULL,
    periodo_desde DATE NOT NULL,
    periodo_hasta DATE NOT NULL,
    fecha_limite_presentacion DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    generado_at TIMESTAMPTZ,
    validado_at TIMESTAMPTZ,
    presentado_at TIMESTAMPTZ,
    identificador_presentacion VARCHAR(150),
    evidencia_uri TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_balance_controlado PRIMARY KEY (id),
    CONSTRAINT uk_balance_controlado_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_balance_controlado_periodo UNIQUE (tenant_id, establecimiento_id, clasificacion_controlada_codigo, periodo_desde, periodo_hasta),
    CONSTRAINT uk_balance_controlado_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_balance_controlado_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id) REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT fk_balance_controlado_clasif FOREIGN KEY (clasificacion_controlada_codigo) REFERENCES sch_farmacia.clasificacion_controlada(codigo),
    CONSTRAINT ck_balance_controlado_fechas CHECK (periodo_hasta >= periodo_desde),
    CONSTRAINT ck_balance_controlado_estado CHECK (estado IN ('BORRADOR','GENERADO','VALIDADO','PRESENTADO','OBSERVADO','RECTIFICADO'))
);

CREATE TABLE sch_farmacia.balance_controlado_linea (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    balance_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    existencia_inicial NUMERIC(18,4) NOT NULL DEFAULT 0,
    entradas NUMERIC(18,4) NOT NULL DEFAULT 0,
    salidas NUMERIC(18,4) NOT NULL DEFAULT 0,
    ajustes_positivos NUMERIC(18,4) NOT NULL DEFAULT 0,
    ajustes_negativos NUMERIC(18,4) NOT NULL DEFAULT 0,
    existencia_final NUMERIC(18,4) NOT NULL DEFAULT 0,
    CONSTRAINT pk_balance_controlado_linea PRIMARY KEY (id),
    CONSTRAINT uk_balance_controlado_linea UNIQUE (balance_id, sku_id),
    CONSTRAINT fk_balance_controlado_linea_balance FOREIGN KEY (tenant_id, balance_id) REFERENCES sch_farmacia.balance_controlado(tenant_id, id),
    CONSTRAINT fk_balance_controlado_linea_sku FOREIGN KEY (tenant_id, sku_id) REFERENCES sch_farmacia.sku_comercial(tenant_id, id),
    CONSTRAINT ck_balance_linea_cant CHECK (existencia_inicial >= 0 AND entradas >= 0 AND salidas >= 0 AND ajustes_positivos >= 0 AND ajustes_negativos >= 0 AND existencia_final >= 0)
);

CREATE INDEX ix_mov_controlado_fecha ON sch_farmacia.movimiento_controlado(tenant_id, establecimiento_id, fecha_movimiento DESC);
