-- Comprobantes electrónicos y notas de crédito. La modalidad SUNAT/PSE/OSE queda detrás del FiscalPort.

CREATE TABLE sch_farmacia.comprobante_electronico (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    venta_id BIGINT NOT NULL,
    tipo_cpe VARCHAR(20) NOT NULL,
    codigo_tipo_sunat VARCHAR(10),
    serie VARCHAR(20),
    numero BIGINT,
    fecha_emision TIMESTAMPTZ NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    cliente_tipo_documento VARCHAR(20),
    cliente_numero_documento VARCHAR(30),
    cliente_nombre VARCHAR(300),
    cliente_direccion VARCHAR(500),
    total_gravado NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_exonerado NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_inafecto NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_gratuito NUMERIC(18,2) NOT NULL DEFAULT 0,
    descuento_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    impuesto_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    estado_fiscal VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_GENERACION',
    payload_version INTEGER NOT NULL DEFAULT 1,
    payload_interno JSONB NOT NULL DEFAULT '{}'::jsonb,
    hash_documento VARCHAR(200),
    xml_uri TEXT,
    pdf_uri TEXT,
    cdr_uri TEXT,
    codigo_respuesta VARCHAR(100),
    mensaje_respuesta VARCHAR(1500),
    enviado_at TIMESTAMPTZ,
    aceptado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_comprobante_electronico PRIMARY KEY (id),
    CONSTRAINT uk_comprobante_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_comprobante_venta_tipo UNIQUE (tenant_id, venta_id, tipo_cpe),
    CONSTRAINT uk_comprobante_scope_id UNIQUE (tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_comprobante_venta FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, venta_id) REFERENCES sch_farmacia.venta(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT ck_comprobante_tipo CHECK (tipo_cpe IN ('BOLETA','FACTURA')),
    CONSTRAINT ck_comprobante_estado CHECK (estado_fiscal IN ('PENDIENTE_GENERACION','GENERADO','PENDIENTE_ENVIO','ENVIADO','ACEPTADO','OBSERVADO','RECHAZADO','ANULADO','ERROR_TECNICO')),
    CONSTRAINT ck_comprobante_totales CHECK (total_gravado >= 0 AND total_exonerado >= 0 AND total_inafecto >= 0 AND total_gratuito >= 0 AND descuento_total >= 0 AND impuesto_total >= 0 AND total >= 0)
);

CREATE UNIQUE INDEX uk_comprobante_numeracion ON sch_farmacia.comprobante_electronico(tenant_id, empresa_id, tipo_cpe, serie, numero) WHERE serie IS NOT NULL AND numero IS NOT NULL;

CREATE TABLE sch_farmacia.cpe_envio_intento (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    comprobante_id BIGINT NOT NULL,
    numero_intento INTEGER NOT NULL,
    provider VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(160),
    enviado_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    respondido_at TIMESTAMPTZ,
    resultado VARCHAR(30) NOT NULL,
    status_http INTEGER,
    codigo_respuesta VARCHAR(100),
    mensaje_respuesta VARCHAR(1500),
    metadata_sanitizada JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_cpe_envio_intento PRIMARY KEY (id),
    CONSTRAINT uk_cpe_envio_intento UNIQUE (comprobante_id, numero_intento),
    CONSTRAINT fk_cpe_envio_intento_comprobante FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, comprobante_id) REFERENCES sch_farmacia.comprobante_electronico(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT ck_cpe_envio_resultado CHECK (resultado IN ('PENDIENTE','ACEPTADO','OBSERVADO','RECHAZADO','ERROR_TECNICO'))
);

CREATE TABLE sch_farmacia.nota_credito_electronica (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    comprobante_origen_id BIGINT NOT NULL,
    devolucion_id BIGINT,
    codigo_tipo_sunat VARCHAR(10),
    serie VARCHAR(20),
    numero BIGINT,
    motivo_codigo VARCHAR(30) NOT NULL,
    motivo_descripcion VARCHAR(500),
    fecha_emision TIMESTAMPTZ NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    total_impuesto NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    estado_fiscal VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_GENERACION',
    payload_interno JSONB NOT NULL DEFAULT '{}'::jsonb,
    xml_uri TEXT,
    pdf_uri TEXT,
    cdr_uri TEXT,
    codigo_respuesta VARCHAR(100),
    mensaje_respuesta VARCHAR(1500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_nota_credito PRIMARY KEY (id),
    CONSTRAINT uk_nota_credito_uuid UNIQUE (uuid_publico),
    CONSTRAINT fk_nota_credito_cpe FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, comprobante_origen_id) REFERENCES sch_farmacia.comprobante_electronico(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT fk_nota_credito_devolucion FOREIGN KEY (tenant_id, empresa_id, establecimiento_id, devolucion_id) REFERENCES sch_farmacia.devolucion_comercial(tenant_id, empresa_id, establecimiento_id, id),
    CONSTRAINT ck_nota_credito_total CHECK (total >= 0 AND total_impuesto >= 0),
    CONSTRAINT ck_nota_credito_estado CHECK (estado_fiscal IN ('PENDIENTE_GENERACION','GENERADO','PENDIENTE_ENVIO','ENVIADO','ACEPTADO','OBSERVADO','RECHAZADO','ANULADO','ERROR_TECNICO'))
);

CREATE UNIQUE INDEX uk_nota_credito_numeracion ON sch_farmacia.nota_credito_electronica(tenant_id, empresa_id, serie, numero) WHERE serie IS NOT NULL AND numero IS NOT NULL;
