-- ERP boundary: documentos proveedor, tesorería/CxP/CxC, posting retail y Observatorio.

CREATE TABLE sch_farmacia.cuenta_bancaria_empresa (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    banco VARCHAR(150) NOT NULL,
    tipo_cuenta VARCHAR(30),
    numero_cuenta VARCHAR(100) NOT NULL,
    cci VARCHAR(100),
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    alias VARCHAR(100),
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cuenta_bancaria_empresa PRIMARY KEY (id),
    CONSTRAINT uk_cuenta_bancaria_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_cuenta_bancaria UNIQUE (tenant_id, empresa_id, banco, numero_cuenta),
    CONSTRAINT fk_cuenta_bancaria_empresa FOREIGN KEY (tenant_id, empresa_id) REFERENCES sch_farmacia.empresa_operadora(tenant_id, id),
    CONSTRAINT ck_cuenta_bancaria_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE sch_farmacia.factura_proveedor (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    orden_compra_id BIGINT,
    tipo_documento VARCHAR(20) NOT NULL,
    serie VARCHAR(20) NOT NULL,
    numero VARCHAR(30) NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_recepcion DATE,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    tipo_cambio NUMERIC(18,6),
    subtotal NUMERIC(18,2) NOT NULL DEFAULT 0,
    descuento_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    impuesto_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    total NUMERIC(18,2) NOT NULL,
    fecha_vencimiento DATE,
    estado_matching VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    diferencia_matching JSONB NOT NULL DEFAULT '{}'::jsonb,
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADA',
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_factura_proveedor PRIMARY KEY (id),
    CONSTRAINT uk_factura_proveedor_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_factura_proveedor_doc UNIQUE (tenant_id, proveedor_id, tipo_documento, serie, numero),
    CONSTRAINT uk_factura_proveedor_scope_id UNIQUE (tenant_id, empresa_id, id),
    CONSTRAINT fk_factura_proveedor_proveedor FOREIGN KEY (tenant_id, proveedor_id) REFERENCES sch_farmacia.proveedor(tenant_id, id),
    CONSTRAINT fk_factura_proveedor_oc FOREIGN KEY (tenant_id, empresa_id, orden_compra_id) REFERENCES sch_farmacia.orden_compra(tenant_id, empresa_id, id),
    CONSTRAINT ck_factura_proveedor_total CHECK (subtotal >= 0 AND descuento_total >= 0 AND impuesto_total >= 0 AND total >= 0),
    CONSTRAINT ck_factura_matching CHECK (estado_matching IN ('PENDIENTE','COINCIDENTE','CON_DIFERENCIAS','APROBADO_EXCEPCION')),
    CONSTRAINT ck_factura_proveedor_estado CHECK (estado IN ('REGISTRADA','APROBADA','OBSERVADA','ANULADA'))
);

CREATE TABLE sch_farmacia.cuenta_por_pagar (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    factura_proveedor_id BIGINT NOT NULL,
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_vencimiento DATE,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    monto_total NUMERIC(18,2) NOT NULL,
    monto_pagado NUMERIC(18,2) NOT NULL DEFAULT 0,
    saldo NUMERIC(18,2) GENERATED ALWAYS AS (monto_total - monto_pagado) STORED,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    erp_external_id VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cuenta_por_pagar PRIMARY KEY (id),
    CONSTRAINT uk_cuenta_por_pagar_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_cuenta_por_pagar_factura UNIQUE (factura_proveedor_id),
    CONSTRAINT fk_cuenta_por_pagar_factura FOREIGN KEY (tenant_id, empresa_id, factura_proveedor_id) REFERENCES sch_farmacia.factura_proveedor(tenant_id, empresa_id, id),
    CONSTRAINT ck_cuenta_por_pagar_montos CHECK (monto_total >= 0 AND monto_pagado >= 0 AND monto_pagado <= monto_total),
    CONSTRAINT ck_cuenta_por_pagar_estado CHECK (estado IN ('PENDIENTE','PARCIAL','PAGADA','BLOQUEADA','ANULADA'))
);

CREATE TABLE sch_farmacia.pago_cuenta_por_pagar (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    cuenta_por_pagar_id BIGINT NOT NULL,
    cuenta_bancaria_id BIGINT,
    fecha_pago TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto NUMERIC(18,2) NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    referencia VARCHAR(150),
    estado VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO',
    created_by VARCHAR(100) NOT NULL,
    CONSTRAINT pk_pago_cxp PRIMARY KEY (id),
    CONSTRAINT uk_pago_cxp_uuid UNIQUE (uuid_publico),
    CONSTRAINT fk_pago_cxp_cuenta FOREIGN KEY (cuenta_por_pagar_id) REFERENCES sch_farmacia.cuenta_por_pagar(id),
    CONSTRAINT fk_pago_cxp_banco FOREIGN KEY (cuenta_bancaria_id) REFERENCES sch_farmacia.cuenta_bancaria_empresa(id),
    CONSTRAINT ck_pago_cxp_monto CHECK (monto > 0),
    CONSTRAINT ck_pago_cxp_estado CHECK (estado IN ('REGISTRADO','CONFIRMADO','ANULADO','EXTORNADO'))
);

CREATE TABLE sch_farmacia.cuenta_por_cobrar (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    cliente_id BIGINT,
    venta_id BIGINT,
    comprobante_id BIGINT,
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_vencimiento DATE,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    monto_total NUMERIC(18,2) NOT NULL,
    monto_cobrado NUMERIC(18,2) NOT NULL DEFAULT 0,
    saldo NUMERIC(18,2) GENERATED ALWAYS AS (monto_total - monto_cobrado) STORED,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cuenta_por_cobrar PRIMARY KEY (id),
    CONSTRAINT uk_cuenta_por_cobrar_uuid UNIQUE (uuid_publico),
    CONSTRAINT fk_cxc_cliente FOREIGN KEY (tenant_id, cliente_id) REFERENCES sch_farmacia.cliente(tenant_id, id),
    CONSTRAINT fk_cxc_venta FOREIGN KEY (tenant_id, venta_id) REFERENCES sch_farmacia.venta(tenant_id, id),
    CONSTRAINT fk_cxc_cpe FOREIGN KEY (comprobante_id) REFERENCES sch_farmacia.comprobante_electronico(id),
    CONSTRAINT ck_cxc_montos CHECK (monto_total >= 0 AND monto_cobrado >= 0 AND monto_cobrado <= monto_total),
    CONSTRAINT ck_cxc_estado CHECK (estado IN ('PENDIENTE','PARCIAL','COBRADA','VENCIDA','ANULADA'))
);

CREATE TABLE sch_farmacia.posting_retail (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    tipo_origen VARCHAR(30) NOT NULL,
    origen_uuid UUID NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    fecha_contable DATE NOT NULL,
    payload_posting JSONB NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    external_id VARCHAR(150),
    numero_intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_error VARCHAR(1500),
    confirmado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_posting_retail PRIMARY KEY (id),
    CONSTRAINT uk_posting_retail_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_posting_retail_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_posting_retail_estado CHECK (estado IN ('PENDIENTE','EN_PROCESO','CONFIRMADO','ERROR_REINTENTABLE','ERROR_DEFINITIVO','REVERSADO'))
);

CREATE TABLE sch_farmacia.reporte_mensual_precios (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    uuid_publico UUID NOT NULL DEFAULT uuidv7(),
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    periodo DATE NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'BORRADOR',
    generado_at TIMESTAMPTZ,
    validado_at TIMESTAMPTZ,
    enviado_at TIMESTAMPTZ,
    mecanismo VARCHAR(80),
    identificador_envio VARCHAR(150),
    evidencia_uri TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reporte_mensual_precios PRIMARY KEY (id),
    CONSTRAINT uk_reporte_mensual_precios_uuid UNIQUE (uuid_publico),
    CONSTRAINT uk_reporte_mensual_periodo UNIQUE (tenant_id, empresa_id, periodo),
    CONSTRAINT uk_reporte_mensual_scope_id UNIQUE (tenant_id, empresa_id, id),
    CONSTRAINT fk_reporte_mensual_empresa FOREIGN KEY (tenant_id, empresa_id) REFERENCES sch_farmacia.empresa_operadora(tenant_id, id),
    CONSTRAINT ck_reporte_mensual_estado CHECK (estado IN ('BORRADOR','GENERADO','VALIDADO','ENVIADO','OBSERVADO','RECTIFICADO'))
);

CREATE TABLE sch_farmacia.reporte_mensual_precios_linea (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    reporte_id BIGINT NOT NULL,
    establecimiento_id BIGINT NOT NULL,
    producto_regulado_id BIGINT,
    sku_id BIGINT NOT NULL,
    precio NUMERIC(18,4) NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'PEN',
    fuente_precio VARCHAR(100) NOT NULL,
    version_precio VARCHAR(100),
    CONSTRAINT pk_reporte_mensual_precios_linea PRIMARY KEY (id),
    CONSTRAINT uk_reporte_mensual_precios_linea UNIQUE (reporte_id, establecimiento_id, sku_id),
    CONSTRAINT fk_reporte_mensual_linea_reporte FOREIGN KEY (tenant_id, empresa_id, reporte_id) REFERENCES sch_farmacia.reporte_mensual_precios(tenant_id, empresa_id, id),
    CONSTRAINT fk_reporte_mensual_linea_est FOREIGN KEY (tenant_id, empresa_id, establecimiento_id) REFERENCES sch_farmacia.establecimiento_farmaceutico(tenant_id, empresa_id, id),
    CONSTRAINT fk_reporte_mensual_linea_producto FOREIGN KEY (producto_regulado_id) REFERENCES sch_farmacia.producto_regulado(id),
    CONSTRAINT fk_reporte_mensual_linea_sku FOREIGN KEY (tenant_id, sku_id) REFERENCES sch_farmacia.sku_comercial(tenant_id, id),
    CONSTRAINT ck_reporte_mensual_precio CHECK (precio >= 0)
);

CREATE INDEX ix_cxp_estado ON sch_farmacia.cuenta_por_pagar(tenant_id, estado, fecha_vencimiento);
CREATE INDEX ix_cxc_estado ON sch_farmacia.cuenta_por_cobrar(tenant_id, estado, fecha_vencimiento);
CREATE INDEX ix_posting_estado ON sch_farmacia.posting_retail(tenant_id, estado, created_at);
