plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

dependencies {
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
    options.compilerArgs.addAll(['-parameters', '-Xlint:all'])
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}
