plugins {
    id 'boticas.test'
    id 'jacoco'
}

jacoco {
    toolVersion = '0.8.14'
}

tasks.named('jacocoTestReport') {
    dependsOn tasks.named('test')
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.named('check') {
    dependsOn tasks.named('jacocoTestReport')
}
